// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphe5NBSizL2wWjOmjZZEBZ6Ue1-b1Tr0',
    appId: '1:384940811646:web:ae57582cbe91047ae7ff2f',
    messagingSenderId: '384940811646',
    projectId: 'shopper-398d0',
    authDomain: 'shopper-398d0.firebaseapp.com',
    storageBucket: 'shopper-398d0.appspot.com',
    measurementId: 'G-XP1GN0KF3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzf7Cjd06O-MkPO-jca24EYmGyikVvhQ',
    appId: '1:384940811646:android:b34cffdc9b0f8075e7ff2f',
    messagingSenderId: '384940811646',
    projectId: 'shopper-398d0',
    storageBucket: 'shopper-398d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDka3IsjsmkTrfgFndQOzlE9kjvD1tio90',
    appId: '1:384940811646:ios:9be7f277003c78b6e7ff2f',
    messagingSenderId: '384940811646',
    projectId: 'shopper-398d0',
    storageBucket: 'shopper-398d0.appspot.com',
    iosClientId: '384940811646-0u5irf59cfos3pbe9r2qd3r04dvva4k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDka3IsjsmkTrfgFndQOzlE9kjvD1tio90',
    appId: '1:384940811646:ios:9be7f277003c78b6e7ff2f',
    messagingSenderId: '384940811646',
    projectId: 'shopper-398d0',
    storageBucket: 'shopper-398d0.appspot.com',
    iosClientId: '384940811646-0u5irf59cfos3pbe9r2qd3r04dvva4k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppers',
  );
}
